name: rmake.bat

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install cmake and conan
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: pip install --user -r requirements.txt

      - name: Install Doxygen
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          Invoke-WebRequest -Uri https://doxygen.nl/files/doxygen-1.9.1.windows.x64.bin.zip -OutFile doxygen.zip
          Expand-Archive -LiteralPath doxygen.zip

      - name: Install Wix extension for Visual Studio
        run: |
          Invoke-WebRequest -Uri https://github.com/wixtoolset/VisualStudioExtension/releases/download/v1.0.0.4/Votive2019.vsix -OutFile Votive2019.vsix
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VSIXInstaller" /quiet Votive2019.vsix

      - name: Install Wix Toolset
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          Invoke-WebRequest -Uri https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip -OutFile wix.zip
          Expand-Archive -LiteralPath wix.zip

      # Conan maintains its own cache in ~/.conan/data. Poco takes a long time to build from source. If
      # the version and options have not changed, Conan will not build Poco if it finds it in cache. It
      # will update the cache any time it needs to rebuild Poco. This should only happen when the
      # conanfile.py changes as long as the recipe pins to a specific version of Poco.
      - name: Restore Conan cache, profiles, settings
        uses: actions/cache@v2
        with:
          path: ~/.conan/data
          key: ${{ runner.os }}-vs16-conan-data-${{ hashFiles('conanfile.py') }}

      - name: Set up default conan profile
        run: C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts\conan profile new default --detect

      - name: 64-bit Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          .\ci.bat 64

      - name: 32-bit Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          .\ci.bat 32

      - name: Generate docs
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          Set-Location BranchSDK
          ..\doxygen\doxygen.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: BranchSDK/docs
